<?php

namespace common\models\log;

use common\models\utils\DateUtil;
use Yii;

/**
 * This is the model class for table "Log".
 *
 * @property int $log_id
 * @property string $log_time_stamp
 * @property string $log_message
 */
class Log extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'Log';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['log_message'], 'required'],
            [['log_message'], 'protected'],
            [['log_message'], 'string', 'max' => 255],
        ];
    }

    public function beforeSave($insert)
    {
        $this->log_date = DateUtil::getLocalTime();
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'log_id' => Yii::t('app', 'Log ID'),
            'log_message' => Yii::t('app', 'Log Message'),
        ];
    }

    /**
     * @inheritdoc
     * @return \common\models\log\query\LogQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\log\query\LogQuery(get_called_class());
    }
}
